ALTER TABLE video
    ADD COLUMN content_type VARCHAR(32) NOT NULL DEFAULT 'GENERAL' AFTER status,
    ADD COLUMN import_cookie_path VARCHAR(1024) AFTER content_type;

ALTER TABLE summary
    ADD COLUMN updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) AFTER created_at,
    ADD COLUMN user_edited TINYINT(1) NOT NULL DEFAULT 0 AFTER updated_at;
